# Generated by Django 5.0.6 on 2024-08-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcut',
            new_name='Product',
        ),
    ]
