# Generated by Django 5.1 on 2024-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('1', 'State: 1'), ('2', 'Madhesh'), ('3', 'Bagmati'), ('4', 'Gandaki'), ('5', 'Lumbini'), ('6', 'Karnali'), ('7', 'Sudurpaschim')], max_length=100),
        ),
    ]
